version: '1'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rambo12345
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: